POST http://localhost:3000/api/topics/submit
Content-Type: application/json

{
  "name": "کافه نمونه",
  "type": "business",
  "description": "یک کافه خوب برای تست ثبت نظر در نظرمن",
  "citySlug": "tehran",
  "firstComment": "تجربه خوبی داشتم"
}